domain_path: D:\Programs\FPGA\Vitis\ZYNQ_DRAM_test\platform111\export\platform111\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\2025.1\Vitis\data\embeddedsw\lib\sw_apps\zynq_dram_test
template: zynq_dram_test
lang: c
